# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-29 07:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('account_code', models.CharField(max_length=50, unique=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('accept_language', models.CharField(blank=True, max_length=6, null=True)),
                ('state', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=20)),
                ('hosted_login_token', models.CharField(blank=True, max_length=32, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurly_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='BillingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('type', models.CharField(blank=True, choices=[('credit_card', 'Credit Card'), ('paypal', 'PayPal')], max_length=50, null=True)),
                ('company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('address1', models.CharField(blank=True, max_length=200, null=True)),
                ('address2', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('zip', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('vat_number', models.CharField(blank=True, max_length=16, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('ip_address_country', models.CharField(blank=True, max_length=2, null=True)),
                ('card_type', models.CharField(blank=True, max_length=50, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('first_six', models.IntegerField(blank=True, null=True)),
                ('last_four', models.IntegerField(blank=True, null=True)),
                ('start_month', models.IntegerField(blank=True, null=True)),
                ('start_year', models.IntegerField(blank=True, null=True)),
                ('issue_number', models.IntegerField(blank=True, null=True)),
                ('billing_agreement_id', models.CharField(blank=True, max_length=100, null=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_info', to='django_recurly.Account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, max_length=40, unique=True)),
                ('invoice_id', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('action', models.CharField(choices=[('verify', 'Verify'), ('purchase', 'Purchase'), ('refund', 'Refund')], max_length=10)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('void', 'Void')], max_length=10)),
                ('source', models.CharField(choices=[('transaction', 'One-time transaction'), ('subscription', 'Subscription'), ('billing_info', 'Updated billing info')], max_length=100)),
                ('amount_in_cents', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.CharField(max_length=250)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('xml', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_recurly.Account')),
            ],
            options={
                'ordering': ['-id'],
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=40, unique=True)),
                ('plan_code', models.CharField(max_length=100)),
                ('plan_version', models.IntegerField(default=1)),
                ('state', models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('expired', 'Expired')], default='active', max_length=20)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_amount_in_cents', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_started_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_ends_at', models.DateTimeField(blank=True, null=True)),
                ('trial_started_at', models.DateTimeField(blank=True, null=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('xml', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_recurly.Account')),
            ],
            options={
                'ordering': ['-id'],
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('token', models.CharField(max_length=40, unique=True)),
                ('cls', models.CharField(choices=[('subscription', 'Subscription'), ('billing_info', 'Billing Info'), ('invoice', 'Invoice')], max_length=12)),
                ('identifier', models.CharField(max_length=40)),
                ('xml', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='django_recurly.Account')),
            ],
            options={
                'abstract': False,
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
            },
        ),
    ]
