# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-02 08:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_recurly', '0002_auto_20171019_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billinginfo',
            name='first_six',
        ),
    ]
