# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-08 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_recurly', '0003_remove_billinginfo_first_six'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='collection_method',
            field=models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='automatic', max_length=20),
        ),
    ]
