# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-04 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_recurly', '0003_auto_20171004_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billinginfo',
            old_name='company_name',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='billinginfo',
            old_name='billing_agreement_id',
            new_name='paypal_billing_agreement_id',
        ),
        migrations.RemoveField(
            model_name='billinginfo',
            name='issue_number',
        ),
        migrations.RemoveField(
            model_name='billinginfo',
            name='start_month',
        ),
        migrations.RemoveField(
            model_name='billinginfo',
            name='start_year',
        ),
        migrations.AddField(
            model_name='billinginfo',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
