# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-05 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_recurly', '0004_auto_20171004_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billinginfo',
            name='type',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='plan_version',
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan_name',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='subscription',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billinginfo',
            name='address1',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='billinginfo',
            name='address2',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='billinginfo',
            name='card_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='billinginfo',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='billinginfo',
            name='company',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='billinginfo',
            name='country',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='billinginfo',
            name='ip_address_country',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='billinginfo',
            name='paypal_billing_agreement_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='billinginfo',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='billinginfo',
            name='state',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='billinginfo',
            name='vat_number',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='billinginfo',
            name='zip',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan_code',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='state',
            field=models.CharField(choices=[('future', 'Future'), ('active', 'Active'), ('canceled', 'Canceled'), ('expired', 'Expired')], default='active', max_length=20),
        ),
    ]
