# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-13 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_recurly', '0005_subscription_imported_trial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
