# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-17 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_recurly', '0006_auto_20171113_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='started_with_gift',
            field=models.BooleanField(default=False),
        ),
    ]
