# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-05 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_recurly', '0006_auto_20171005_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='tax_exempt',
            field=models.NullBooleanField(default=False),
        ),
    ]
