# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-01-17 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_recurly', '0007_subscription_started_with_gift'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='legacy_starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
