# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-07-11 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_recurly', '0008_subscription_legacy_starts_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='has_past_due_invoice',
            field=models.NullBooleanField(default=None),
        ),
    ]
