# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-16 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_recurly', '0009_auto_20171013_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_provisioning_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
