# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2020-07-03 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_recurly', '0009_account_has_past_due_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionAddOn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_on_code', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_amount_in_cents', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_add_ons', to='django_recurly.Subscription')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
